### PR TITLE
Allow to specify a level to log

### PR DESCRIPTION
**Pull request by mweibel**
Limits the number of messages being sent to graylog.

### CODE REVIEW

**Comment by ubirajaramneto** [comment]
Hey there!

Thanks a lot for your PR, I'm going to review it as soon as I have some spare time and merge it.

Wasn't aware there was some activity on this project hehe.

Again, thanks a lot.

**Comment by ubirajaramneto** [comment]
mweibel, after reviewing the changes you made, I noted a couple of things that could bring confusion.

First, in the README, the modifications you made do not state that the new option will prevent sending messages with certain log levels, I believe this is crucial since this will change the behavior of how the plugin sends the GELF payload.

Second, I don't think line 39 in /index.js file on the register function should be there, since the level is already set to an int when the gelfFactory returns the GELF payload to be sent.

Until you can come up with a solution for these 2 points, mainly the first point I mentioned, this PR will be on hold since it will change behavior.

Please let me know your thoughts and suggestions, I would love to hear them.

Let me know if you have any questions and I'll be glad to answer them.

**Comment by mweibel** [comment]
Thanks for reviewing.

> First, in the README, the modifications you made do not state that the new option will prevent sending messages with certain log levels, I believe this is crucial since this will change the behavior of how the plugin sends the GELF payload.

Do you have a preference for how to describe that? In all other logging libs it's usually clear when you specify a log level that it'll only write logs of equal or higher importance.

> Second, I don't think line 39 in /index.js file on the register function should be there, since the level is already set to an int when the gelfFactory returns the GELF payload to be sent.

What we give to the config options object is a string representation of the level. What we need later on in order to compare the levels is the integer representation of it in order to be able to check if the log to be sent should be written or not. That's why this is there.

**Comment by ubirajaramneto** [comment]
On the documentation part, just make it clear that adding the additional log level option will block certain logs to be sent, I really want the docs to be understood even by the most junior devs.

On the parse function, you got me thinking, the plugin is really small and it could live on the index.js file, however I just don't like the idea of exposing the parsing function to the index, maybe we could figure out how to make this functionality happen but without throwing stuff to the index. I'm open to suggestions here, unfortunately I did not had the time to think of a solution for this, I would love if you could come up with something simple, even if it means adding more stuff to other parts of the plugin.

Let me know your thoughts on this.

**Comment by mweibel** [comment]
I fixed the README.

I don't see how we could make this work in a different way. It's the most simple option given the current structure of the plugin. 
The easiest way to make all of this even simpler is by adding a dependency to [node-graylog2](https://github.com/Wizcorp/node-graylog2) and basicly just invoking this dependency. Obviously this introduces complexity in the sense of a dependency but on the other hand lots of things are cared for. 
If that's something you'd be open to I'd be willing to make such a PR, but separate from the other two open right now.

**Comment by ubirajaramneto** [comment]
node-graylog2 was the reason I wrote this plugin, so no thanks, I wont be adding node-graylog2 as a dependency to this project.

I'll try to think of something tonight, thanks for the fix on the readme :)

**Comment by mweibel** [comment]
> node-graylog2 was the reason I wrote this plugin, so no thanks, I wont be adding node-graylog2 as a dependency to this project

Could you elaborate on this?

> I'll try to think of something tonight, thanks for the fix on the readme :)

You repeatadly said you don't have much time to maintain this repo. I totally understand this and know how it is as I have several open source packages as well. However I wonder why you insist to change the way this is implemented so much. Seems like a minor isssue to me.

**Comment by ubirajaramneto** [comment]
It is a minor issue indeed, don't get me wrong. The thing is I just think this is not a good solution in terms of organization, nothing big at all.

I'll merge both requests today as I have some spare time (finally).

I think I can merge them now and come back at them and refactor if I find it's needed in the future.

Anyways thanks a lot for the help, really appreciate it.

**Pull request merged**
