### PR TITLE
Fix using wrong name for import

### PR DESCRIPTION
**Pull request by mweibel**

### CODE REVIEW

**Comment by mweibel** [comment]
@ubirajaramneto unfortunately the current implementation doesn't work like this :/

**Comment by ubirajaramneto** [comment]
Sorry for the delay, I am not maintaining this module anymore.

I will provide whatever support you guys need tho.

Btw, if you are interested we could work on updating this project to the new hapi.js standard, but I guess not many people use this module anymore.

**Comment by mweibel** [comment]
No worries, thanks for merging :) Could you publish a new version too, please?

I'd also take over maintaining as I'm actively using it. You decide. 
Upgrading: we're still on the older version of hapi, too. So that's not in my current wishlist, yet :)

**Comment by ubirajaramneto** [comment]
Sure, I can give you rights to maintain this one.

If you need help just ask away and I will try to help as much as I can.

I am going to bump the minor version for this one.

**Comment by ubirajaramneto** [comment]
Ok I just pushed a new tag and published a new version on NPM, let me know if you need anything else.

**Comment by mweibel** [comment]
Awesome, thanks!

**Pull request merged**
